# Generated by Django 5.0.14 on 2026-08-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone_number", models.CharField(max_length=32)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("preferred_language", models.CharField(blank=True, max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="end_users",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="enduser",
            constraint=models.UniqueConstraint(
                fields=("tenant", "phone_number"), name="unique_tenant_phone_number"
            ),
        ),
    ]
