# Generated by Django 5.0.14 on 2026-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="context_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="context_summary_through_message_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
