# Generated by Django 5.0.14 on 2026-08-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("google", "Google"),
                            ("outlook", "Outlook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_calendar_id", models.CharField(max_length=255)),
                ("access_token", models.BinaryField()),
                ("refresh_token", models.BinaryField()),
                ("token_expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connection",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
